version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE='project'
      - MYSQL_ROOT_PASSWORD='MyPassword'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqldata/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysqldata:
  pgdata:
  redisdata:
